CREATE TABLE IF NOT EXISTS FACT_DAILY_GMV_SUBSIDIARY (
	TRANSACTION_DATE DATE NOT NULL,
	SUBSIDIARY_ID STRING NOT NULL,
	GMV_AMOUNT DECIMAL(18,2) NOT NULL,
	TRANSACTION_COUNT BIGINT NOT NULL,
	PROCESSING_DATE DATE NOT NULL, -- DATA DO PROCESSAMENTO (D-1)
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NULL,
PRIMARY KEY (TRANSACTION_DATE, SUBSIDIARY_ID, PROCESSING_DATE)
)
USING DELTA
PARTITIONED BY (TRANSACTION_DATE); 