SELECT
    TRANSACTION_DATE,
    SUBSIDIARY,
    GMV_AMOUNT,
    TRANSACTION_COUNT,
    PROCESSING_DATE,
    CREATED_AT
FROM FACT_DAILY_GMV_SUBSIDIARY
WHERE PROCESSING_DATE = (
    SELECT MAX(PROCESSING_DATE)
    FROM FACT_DAILY_GMV_SUBSIDIARY
)
ORDER BY TRANSACTION_DATE, SUBSIDIARY; 