CREATE TABLE IF NOT EXISTS FACT_DAILY_GMV_SUBSIDIARY (
	TRANSACTION_DATE DATE NOT NULL,
	SUBSIDIARY VARCHAR(15) NOT NULL,
	GMV_AMOUNT DECIMAL(18,2) NOT NULL,
	TRANSACTION_COUNT BIGINT NOT NULL,
	PROCESSING_DATE DATE NOT NULL, -- DATA DO PROCESSAMENTO (D-1)
	TRANSACTION_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NULL
)
USING DELTA
PARTITIONED BY (TRANSACTION_DATE); 