SELECT
	P.PRODUCER_ID,
	SUM(PI.PURCHASE_VALUE * PI.ITEM_QUANTITY) AS TOTAL_BILLING
FROM
	PURCHASE P
JOIN PRODUCT_ITEM PI ON
	P.PROD_ITEM_ID = PI.PROD_ITEM_ID
WHERE
	P.ORDER_DATE BETWEEN '2021-01-01' AND '2021-12-31'
GROUP BY
	P.PRODUCER_ID 
ORDER BY
	TOTAL_BILLING DESC
LIMIT 50;