SELECT
    TRANSACTION_DATE,
    SUBSIDIARY_ID,
    GMV_AMOUNT,
    TRANSACTION_COUNT
FROM FACT_DAILY_GMV_SUBSIDIARY
WHERE PROCESSING_DATE = (
    SELECT MAX(PROCESSING_DATE)
    FROM FACT_DAILY_GMV_SUBSIDIARY
)
ORDER BY TRANSACTION_DATE, SUBSIDIARY_ID; 